### ISSUE TITLE
cli error when creating feed that already exists

### ISSUE THREAD

**Issue by giovino** [csirtgadgets/py-csirtgsdk#69]
when using the cli to create a feed that already exists, turns an ugly error. 

```
$ csirtg --user user --new --feed larry1 -v
2016-01-27 16:29:42,137 - INFO - csirtgsdk.client[288] - Creating feed larry1 for user user
2016-01-27 16:29:42,142 - INFO - requests.packages.urllib3.connectionpool[735] - Starting new HTTPS connection (1): csirtg.io
/home/user/code/py-csirtgsdk/venv/local/lib/python2.7/site-packages/requests-2.6.2-py2.7.egg/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "/home/user/code/py-csirtgsdk/venv/bin/csirtg", line 9, in <module>
    load_entry_point('csirtgsdk==0.0.0a1-109.gfcb38d9.dirty', 'console_scripts', 'csirtg')()
  File "/home/user/code/py-csirtgsdk/csirtgsdk/client.py", line 289, in main
    feed = Feed(cli).new(options['user'], options['feed'], description=options['description'])
  File "/home/user/code/py-csirtgsdk/csirtgsdk/feed.py", line 27, in new
    body = self.client.post(uri, data)
  File "/home/user/code/py-csirtgsdk/csirtgsdk/client.py", line 96, in post
    body = self.session.post(uri, data=data, verify=self.verify_ssl)
  File "/home/user/code/py-csirtgsdk/venv/local/lib/python2.7/site-packages/requests-2.6.2-py2.7.egg/requests/sessions.py", line 508, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/user/code/py-csirtgsdk/venv/local/lib/python2.7/site-packages/requests-2.6.2-py2.7.egg/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/user/code/py-csirtgsdk/venv/local/lib/python2.7/site-packages/requests-2.6.2-py2.7.egg/requests/sessions.py", line 594, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/home/user/code/py-csirtgsdk/venv/local/lib/python2.7/site-packages/requests-2.6.2-py2.7.egg/requests/sessions.py", line 196, in resolve_redirects
    **adapter_kwargs
  File "/home/user/code/py-csirtgsdk/venv/local/lib/python2.7/site-packages/requests-2.6.2-py2.7.egg/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/home/user/code/py-csirtgsdk/venv/local/lib/python2.7/site-packages/requests-2.6.2-py2.7.egg/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ResponseNotReady())
```

**Comment by giovino** [comment]
looks like the app is returning a 303.. 

```
$ curl -i -XPOST -H "Accept: application/vnd.csirtg.v0" -H "Authorization: Token token=<redacted>" -H "Content-Type: application/json" https://csirtg.io/api/users/giovino/feeds -d '{"feed": { "name": "larry1", "description": "spyeye bad" } }'

HTTP/1.1 303 See Other
Cache-Control: no-cache
Content-Type: application/json; charset=utf-8
Date: Fri, 29 Jan 2016 19:00:15 GMT
Location: /api/users/giovino/feeds/larry1
Server: nginx/1.8.0 + Phusion Passenger 4.0.59
Status: 303 See Other
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Powered-By: Phusion Passenger 4.0.59
X-Request-Id: 101db6c1-3494-4b01-8106-2e7e49be945d
X-Runtime: 0.016879
X-XSS-Protection: 1; mode=block
transfer-encoding: chunked
Connection: keep-alive
```

**Comment by wesyoung** [comment]
is a 303 not correct? look at the "Location" header...

**Comment by giovino** [comment]
OK 303 [sounds reasonable](https://en.wikipedia.org/wiki/HTTP_303)

obviously the cli client should not puke.

**Comment by wesyoung** [comment]
have to dig into, requests is throwing that error [probably for good reason]. but if what you're suggesting is a cleaner error, then i think we can do that...

**Comment by wesyoung** [comment]
actually this is correct, i don't think i was specifying the correct location header... rolling out changes to the API and sdk

**Comment by wesyoung** [comment]
good to go.
